- name: Pre-Init system configuration
  ansible.builtin.import_playbook:
    playbooks/system.yml

- name: Setup HAProxy
  ansible.builtin.import_playbook:
    playbooks/haproxy.yml

- name: Install kubernetes tools and runtimes
  ansible.builtin.import_playbook:
    playbooks/common.yml

- name: Cluster init for kubernetes
  ansible.builtin.import_playbook:
    playbooks/cluster_init.yml

- name: Cephadm
  ansible.builtin.import_playbook:
    playbooks/cephadm.yml
