- name: Pre-Init system configuration
  ansible.builtin.import_playbook:
    playbooks/system.yml

- name: Setup HAProxy
  ansible.builtin.import_playbook:
    playbooks/haproxy.yml

- name: Create kubernetes cluster
  ansible.builtin.import_playbook:
    playbooks/common.yml
