- name: Install Cilium
  block:
    - name: Detect cilium installation
      ansible.builtin.stat:
        path: '{{ cilium_install_path }}/cilium'
      register: cilium_binary_presence

    - name: Install Cilium
      when: not cilium_binary_presence.stat.exists
      block:
        - name: Download cilium package
          ansible.builtin.get_url:
            url: '{{ cilium_tar_url }}'
            dest: '/tmp/{{ cilium_tar_name }}'
            mode: '0644'
            checksum: 'sha256:{{ cilium_tar_checksum_url }}'

        - name: Extract cilium package
          become: true
          become_user: root
          become_method: ansible.builtin.sudo
          ansible.builtin.unarchive:
            src: '/tmp/{{ cilium_tar_name }}'
            dest: '{{ cilium_install_path }}'
            remote_src: true

- name: Install hubble
  block:
    - name: Debug
      ansible.builtin.debug:
        var: cilium_hubble
