ssh_private_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
  QyNTUxOQAAACDOXw1OQJoS3yFqe8dOjTV2kVUclo7uRHu3yzG5TMVIowAAAJinOFmUpzhZ
  lAAAAAtzc2gtZWQyNTUxOQAAACDOXw1OQJoS3yFqe8dOjTV2kVUclo7uRHu3yzG5TMVIow
  AAAED/J+1CyoMcI3CV2rvWtN/2A2lVQz+bEW/inGhrvqCyVM5fDU5AmhLfIWp7x06NNXaR
  VRyWju5Ee7fLMblMxUijAAAAD3dyYWl0aEBzdGluZ3JheQECAwQFBg==
  -----END OPENSSH PRIVATE KEY-----


ssh_public_key: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM5fDU5AmhLfIWp7x06NNXaRVRyWju5Ee7fLMblMxUij wraith@stingray
