- name: Add kubernetes repository
  block:
    - name: Gather keyrings dir stat
      ansible.builtin.stat:
        path: '{{ kubetools_keyring_path }}'
      register: keyring_dir

    - name: Create keyrings dir
      ansible.builtin.file:
        path: '{{ kubetools_keyring_path }}'
        state: directory
        mode: '0755'
      when: not keyring_dir.stat.exists

    - name: Add repository apt key for kubernetes
      ansible.builtin.apt_key:
        url: '{{ kubetools_k8s_key_url }}'
        keyring: '{{ kubetools_keyring_name }}'
        state: present

    - name: Create list file for k8s repository
      ansible.builtin.apt_repository:
        repo: '{{ kubetools_repo_str }}'
        state: present
        filename: kubernetes
        update_cache: true

- name: Install k8s packages
  block:
    - name: Install kubernetes tools
      ansible.builtin.apt:
        name: '{{ kubetools_k8s_packages }}'
        state: present
        update_cache: true
        cache_valid_time: 3600

    - name: Hold kubernetes packages
      ansible.builtin.dpkg_selections:
        name: '{{ item }}'
        selection: hold
      with_items: '{{ kubetools_k8s_packages }}'
