- name: Add kubernetes repository
  block:
    - name: Create keyrings dir
      ansible.builtin.file:
        path: '{{ kubetools_keyring_path }}'
        state: directory
        mode: '0755'

    - name: Add repository apt key for kubernetes
      ansible.builtin.apt_key:
        url: '{{ kubetools_k8s_key_url }}'
        keyring: '{{ kubetools_keyring_name }}'
        state: present

    - name: Create list file for k8s repository
      ansible.builtin.apt_repository:
        repo: '{{ kubetools_repo_str }}'
        state: present
        filename: kubernetes
        update_cache: true

- name: Install k8s packages
  block:
    - name: Install kubernetes tools
      ansible.builtin.apt:
        name: '{{ kubetools_k8s_packages }}'
        state: present
        update_cache: true
        cache_valid_time: 3600

    - name: Hold kubernetes packages
      ansible.builtin.dpkg_selections:
        name: '{{ item }}'
        selection: hold
      with_items: '{{ kubetools_k8s_packages }}'

- name: Add alias for kubectl
  ansible.builtin.lineinfile:
    path: /home/kube/.bashrc
    line: 'alias k=kubectl'
    state: present

- name: Update /etc/hosts
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    mode: '0644'

- name: Add completion for bash
  block:
    - name: Add completion for bash (1/2)
      ansible.builtin.command:
        argv:
          - kubectl
          - completion
          - bash
      register: kubectl_bash_completion
      changed_when: false

    - name: Add completion for bash (2/2)
      ansible.builtin.copy:
        dest: '/home/{{ kube_user | default(kubetools_kube_user) }}/.local/share/bash-completion/completions/kubectl'
        mode: '0755'
        owner: '{{ kube_user | default(kubetools_kube_user) }}'
        group: '{{ kube_user | default(kubetools_kube_user) }}'
        content: '{{ kubectl_bash_completion.stdout }}'
