- name: Initialize kubernetes cluster
  hosts: kube-control-1
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  vars:
    kube_user: kube
  roles:
    - kubeinit
    - helm

- name: Join control-plane nodes
  hosts: control,!kube-control-1
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  vars:
    kube_user: kube
  roles:
    - kube_control
    - helm

- name: Join worker nodes
  hosts: workers
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  vars:
    kube_user: kube
  roles:
    - kube_worker
